# Generated by Django 2.1.5 on 2024-06-30 22:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0003_auto_20240630_2211'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quiz',
            old_name='topic_id',
            new_name='topic',
        ),
    ]
